language: python
python: 2.7
sudo: required
dist: trusty
env:
- WHEELHOUSE=$HOME/.cache/wheelhouse PIP_FIND_LINKS=file://$WHEELHOUSE PIP_WHEEL_DIR=$WHEELHOUSE
cache:
  directories:
  - "$HOME/.cache/pip"
  - "$HOME/.cache/wheelhouse"
  - portiaui/node_modules
  - portiaui/bower_components


install:
- source ${VIRTUAL_ENV}/bin/activate
- sudo -H ./provision.sh install_deps install_splash install_python_deps
- sudo -H pip install tox
- python -c 'import splash, qt5reactor' # Check it's in the python path
- cd portiaui
- npm install -g bower
- npm install
- bower install
- cd ..

before_script:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- source ${VIRTUAL_ENV}/bin/activate
- export PYTHONPATH=`pwd`/slybot:`pwd`/slyd
- cd slyd
- python tests/testserver/server.py 2>&1 | grep -v 'HTTP/1.1" 200' &
- cd ..
- sleep 3 # give xvfb some time to start
script:
- cd ./slybot
- sudo -E tox
- cd ../portia_server
- ./manage.py test portia_orm.tests
- ./manage.py test portia_api.tests
- cd ../portiaui
- npm test
before_deploy:
- cd ../slybot
- pip install twine
- sudo chown -R $USER .
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: scrapinghub
  password:
    secure: S5hZT2YBncUSkPTyR5RUQnACfTsW2ZtpHeQucIamKWN+xkE8KK9O0cWUMuKQ0q3U5ShFkZdhO4PnBjvtP54Dq9IogJAudkDJCylctf4qGoIlWu01mAoJzcUfrS5KW+VolF/opBJObwG38EIOOsVy9UYq7DeQcryAAG1RuMjONAk=
  on:
    all_branches: true
    tags: true
    repo: scrapinghub/portia
    condition: "$TRAVIS_TAG =~ ^slybot-[0-9][.][0-9]*"
